#!/bin/bash

# if you have a dependency to update, 
# define the GIT_DEVELOP_DEPENDENCY in you ~/.bashrc
[[ ! -z "${GIT_DEVELOP_DEPENDENCY}" ]] && \
    echo ${GIT_DEVELOP_DEPENDENCY} && \
    cd ${GIT_DEVELOP_DEPENDENCY} && \
    git hard_checkout develop && \
    cd -

git hard_checkout develop
