#!/bin/bash

git fetch

REMOTE=origin
if [ $# -ge 1 ]; then
  if [ $* != *--force* ]; then
    REMOTE=$1
  fi
fi

COMMAND_FLAG=-d
if [[ $* == *--force* ]]
then
  COMMAND_FLAG=-D
fi

git remote prune ${REMOTE} && git branch -vv | cut -c 3- | grep ': gone]' | awk '{print $1}' | xargs -n1 -r echo git branch ${COMMAND_FLAG}
git branch | grep -v "^\*" | xargs -r -n1 echo git branch ${COMMAND_FLAG}
