#!/bin/bash

BRANCH_NAME="${1}"

git stash && \
    git remote update || (echo "ERROR: fetching and updating"; exit 1)
git checkout ${BRANCH_NAME} || git checkout -b ${BRANCH_NAME} origin/${BRANCH_NAME}  || (echo "ERROR: checking out"; exit 1)
git reset --hard origin/${BRANCH_NAME} || (echo "ERROR: resetting to origin's HEAD"; exit 1)
