#!/bin/bash

GIT_REPOS_HOME=$PWD \
    find . -type d -name '.git*' ! -path "*/poky-tmp/*" 2>/dev/null | \
    sed 's/\.git$//g' | \
    xargs -I '{}' sh -c 'readlink -e {};' | \
    uniq | \
    sort | \
    xargs -I '{}' sh -c 'cd {}; echo "dir: $(pwd) url: $(git config --get remote.origin.url) branch: $(git rev-parse --abbrev-ref HEAD) hash: $(git rev-parse HEAD)"; cd $GIT_REPOS_HOME;'
