#!/bin/bash

# if you have a dependency to update, 
# define the GIT_DEVELOP_DEPENDENCY in you ~/.bashrc
[[ ! -z "${GIT_DEVELOP_DEPENDENCY}" ]] && \
[[ -d "${GIT_DEVELOP_DEPENDENCY}" ]] && \
    echo ${GIT_DEVELOP_DEPENDENCY} && \
    cd ${GIT_DEVELOP_DEPENDENCY} && \
    git hard_checkout develop && \
    cd -

if [[ $* == *--next* ]]
then
    git hard_checkout develop_next || exit 1
else
    git hard_checkout develop || exit 1
fi
