#!/bin/bash

git stash
git submodule foreach --recursive git stash
if [[ $* == *--force* ]]
then
    git stash drop
    git submodule foreach --recursive git stash drop
fi
git clean -xdff && git clean -Xdff
git submodule foreach --recursive git clean -xdff && git submodule foreach --recursive git clean -Xdff
