#!/bin/bash

for d in */; do 
    [ -d "${d}"/.git ] && \
    (cd "$d" && TAG="${FOR_EACH_REPO_TAG:-v$(date +%Y%m%d.%H%M%S)-$(git rev-parse --short HEAD)}" && git tag -a "$TAG" -m "Tag from $(date)" && git push origin "$TAG") && \
    echo "$(basename "$d"): $TAG pushed"; 
done
